# Generated by Django 4.2.15 on 2024-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_code', models.CharField(max_length=20, unique=True)),
                ('corp_name', models.CharField(max_length=255)),
                ('stock_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_code', models.CharField(max_length=20, null=True, unique=True)),
                ('stock_code', models.CharField(max_length=10, null=True, unique=True)),
                ('net_income', models.CharField(blank=True, max_length=30, null=True)),
                ('operating_income', models.CharField(blank=True, max_length=30, null=True)),
                ('revenue', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_of_goods_sold', models.CharField(blank=True, max_length=30, null=True)),
                ('total_equity', models.CharField(blank=True, max_length=30, null=True)),
                ('total_assets', models.CharField(blank=True, max_length=30, null=True)),
                ('current_assets', models.CharField(blank=True, max_length=30, null=True)),
                ('current_liabilities', models.CharField(blank=True, max_length=30, null=True)),
                ('cash_and_cash_equivalents', models.CharField(blank=True, max_length=30, null=True)),
                ('accounts_receivable', models.CharField(blank=True, max_length=30, null=True)),
                ('total_liabilities', models.CharField(blank=True, max_length=30, null=True)),
                ('inventory', models.CharField(blank=True, max_length=30, null=True)),
                ('interest_expense', models.CharField(blank=True, max_length=30, null=True)),
                ('stock_times', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock_code', models.CharField(max_length=10)),
                ('close', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('high', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
                ('open', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
