# Generated by Django 4.2.15 on 2024-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock_code', models.CharField(max_length=10)),
                ('stock_name', models.CharField(max_length=100)),
                ('close', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('high', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
                ('open', models.IntegerField(default=0)),
            ],
        ),
    ]
