# Generated by Django 4.2.15 on 2024-10-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_financialstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='corp_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='accounts_receivable',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='average_inventory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='cash_and_cash_equivalents',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='cost_of_goods_sold',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='current_assets',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='current_liabilities',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='interest_expense',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='inventory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='net_income',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='operating_income',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='revenue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='stock_times',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_assets',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_equity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_liabilities',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
