# Generated by Django 4.2.15 on 2024-10-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_financialstatement_corp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='stock_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
