# Generated by Django 4.2.15 on 2024-10-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_financialstatement_stock_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_code', models.CharField(max_length=20, unique=True)),
                ('corp_name', models.CharField(max_length=255)),
                ('stock_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
