# Generated by Django 4.2.15 on 2024-10-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_corpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatement',
            name='average_inventory',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='fiscal_year',
        ),
    ]
